name: Example Workflow
run-name: Example Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Run example script
        run: echo "This job runs every minute."
